"use strict";
module.exports = async (req, res, next) => {
  // Authorization: Token ...tokenKey...
  // Authorization: ApiKey ...tokenKey...
  // Authorization: Bearer ...tokenKey...
  // Authorization: Auth ...tokenKey...
  // Authorization: X-API-KEY ...tokenKey...
  // Authorization: x-auth-token ...tokenKey...
  req.user= null;
  //get token from header
  const auth= req.headers?.authorization || null
  const tokenkey= auth? auth.split(" ") :null
  console.log(auth)
  console.log(tokenkey)
  next()
}
